on: [push, pull_request]
name: Test (Go 1.10)
jobs:
  test:
    env:
      GO111MODULE: off
      GOPATH: ${{ github.workspace }}/go
    strategy:
      matrix:
        go-version: ["1.10"]
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
      - name: Test
        # -d prevents installation, which would fail for Go 1.10
        run: go get -d -t -v ./... && go test -v ./...
        working-directory: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
